### ISSUE TITLE
Freddie be tweakin

### ISSUE THREAD

**Issue by SlickDarnell** [TopGApps/QR-Share-Pro#22]
Yo I been usin this app to move some powder if u know what I mean lil baby. But evah since I use it I been havin some serious issues. Mag boy Freddie been talkin to the fuzz I need u to take him out. Dis for satirical purposes only

**Comment by Visual-Studio-Coder** [comment]
@SlickDarnell 
Slick Darnell, huh? With a profile so bare it looks like a ghost town, you might as well change your name to "No Show." Zero followers and zero public repos? That's a perfect representation of your commitment to contributing anything of substance. It's like you entered the coding world and decided to just hit the snooze button. I mean, come on, at least throw up a project or two to justify your existence on GitHub!

**Comment by aaronhma** [comment]
@SlickDarnell 

Off-topic.
